swagger: '2.0'
info:
  description: Agora Server API Docs
  version: 1.0.0
  title: Agora Wawaji Server
basePath: /v1
tags:
  - name: Machine
    description: Access to Game Machines
schemes:
  - http
paths:
  /machine/:
    post:
      tags:
        - Machine
      summary: start machines, if already started, return machine data directly; in case different uid1 or uid2 is provided, the original process will be restarted with new uid1 and uid2
      operationId: startMachine
      parameters:
        - in: body
          name: machine
          description: The machine to create.
          schema:
            type: object
            required:
              - appid
              - channel
            properties:
              appid:
                type: string
                example: <your appid>
              channel:
                type: string
                example: <your channel>
              appcert:
                type: string
                example: <your app certificate>
              uid1:
                type: integer
                example: 1
              uid2:
                type: integer
                example: 2
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Machine'
              
        '500':
          description: Server Error
definitions:
  Machine:
    type: object
    properties:
      name:
        type: string
        description: Machine name
      video_channel:
        type: string
        description: Machine video channel name
      stream_method:
        type: integer
        description: 'Stream method of machine 0 - Image, 1 - JSMpeg'
        enum:
          - "Image"
          - "JSMpeg"
      video_rotation:
        type: integer
        description: Angles of screen to be rotated
        enum:
          - 0
          - 90
      cameras:
        type: object
        properties:
          main:
            type: string
            description: Url of main camera stream
          sub:
            type: string
            description: Url of sub camera stream